# Tutorial: Machine Learning with Text in scikit-learn

# Note from Donny

This combines: Kevin Markham's Text Learning Tutorial<br>
Some Information from Wikipedia<br>
And some stuff on TF-IDF

## Agenda

1. Model building in scikit-learn (refresher)
2. Representing text as numerical data
3. Reading a text-based dataset into pandas
4. Vectorizing our dataset
5. Building and evaluating a model
6. Comparing models
7. Performing Cross-Validation to select C
8. Tuning the vectorizer (discussion)
9. TF-IDF Vectorizer plus model

## Part 1: Model building in scikit-learn (refresher)

In [526]:
# load the iris dataset as an example
from sklearn.datasets import load_iris
iris = load_iris()

In [527]:
# store the feature matrix (X) and response vector (y)
X = iris.data
y = iris.target

**"Features"** are also known as predictors, inputs, or attributes. The **"response"** is also known as the target, label, or output.

In [528]:
# check the shapes of X and y
print(X.shape)
print(y.shape)

(150, 4)
(150,)


**"Observations"** are also known as samples, instances, or records.

In [529]:
# examine the first 5 rows of the feature matrix (including the feature names)
import pandas as pd
pd.DataFrame(X, columns=iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [530]:
# examine the response vector
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In order to **build a model**, the features must be **numeric**, and every observation must have the **same features in the same order**.

In [531]:
# import the class
from sklearn.neighbors import KNeighborsClassifier

# instantiate the model (with the default parameters)
knn = KNeighborsClassifier()

# fit the model with data (occurs in-place)
knn.fit(X, y)

KNeighborsClassifier()

In order to **make a prediction**, the new observation must have the **same features as the training observations**, both in number and meaning.

In [532]:
# predict the response for a new observation
knn.predict([[3, 5, 4, 2]])

array([1])

## Part 2: Representing text as numerical data

In [533]:
# example text for model training (SMS messages)
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> Text Analysis is a major application field for machine learning algorithms. However the raw data, a sequence of symbols cannot be fed directly to the algorithms themselves as most of them expect **numerical feature vectors with a fixed size** rather than the **raw text documents with variable length**.

We will use [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) to "convert text into a matrix of token counts":

In [534]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [535]:
# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

CountVectorizer()

In [536]:
simple_train

['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [537]:
# examine the fitted vocabulary
vect.get_feature_names_out()

array(['cab', 'call', 'me', 'please', 'tonight', 'you'], dtype=object)

In [538]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 6)>

In [539]:
simple_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 6)>

In [540]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [541]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names_out())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> In this scheme, features and samples are defined as follows:

> - Each individual token occurrence frequency (normalized or not) is treated as a **feature**.
> - The vector of all the token frequencies for a given document is considered a multivariate **sample**.

> A **corpus of documents** can thus be represented by a matrix with **one row per document** and **one column per token** (e.g. word) occurring in the corpus.

> We call **vectorization** the general process of turning a collection of text documents into numerical feature vectors. This specific strategy (tokenization, counting and normalization) is called the **Bag of Words** or "Bag of n-grams" representation. Documents are described by word occurrences while completely ignoring the relative position information of the words in the document.

In [542]:
# check the type of the document-term matrix
type(simple_train_dtm)

scipy.sparse._csr.csr_matrix

In [543]:
# examine the sparse matrix contents
print(simple_train_dtm)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 6)>
  Coords	Values
  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> As most documents will typically use a very small subset of the words used in the corpus, the resulting matrix will have **many feature values that are zeros** (typically more than 99% of them).

> For instance, a collection of 10,000 short text documents (such as emails) will use a vocabulary with a size in the order of 100,000 unique words in total while each document will use 100 to 1000 unique words individually.

> In order to be able to **store such a matrix in memory** but also to **speed up operations**, implementations will typically use a **sparse representation** such as the implementations available in the `scipy.sparse` package.

In [544]:
# example text for model testing
simple_test = ["please don't call me"]

In order to **make a prediction**, the new observation must have the **same features as the training observations**, both in number and meaning.

In [545]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]])

In [546]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names_out())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

**Summary:**

- `vect.fit(train)` **learns the vocabulary** of the training data
- `vect.transform(train)` uses the **fitted vocabulary** to build a document-term matrix from the training data
- `vect.transform(valid)` uses the **fitted vocabulary** to build a document-term matrix from the validation data (and **ignores tokens** it hasn't seen before)

## Part 3: Reading a text-based dataset into pandas

Now you are going to do some things.

In [547]:
# read file into pandas using a relative path sms.tsv
# your code here
path = 'sms.tsv'
sms = pd.read_table(path, header=None, names=['label', 'message'])

Check the .head() as usual, did read_table work correctly? Do you need to set any parameters such as header or names?

We want the columns to have names <i>label</i> and <i>message</i>

In [548]:
# your code here, read the tsv correctly
sms.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [549]:
# examine the shape
sms.shape

(5572, 2)

Examine the first 10 rows

In [550]:
# examine the first 10 rows
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [551]:
# examine the class distribution
sms.columns = ['label', 'message']
sms.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [552]:
# convert label to a numerical variable
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [553]:
# check that the conversion worked
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [554]:
# Identify what will be the response variable and what will be the set of features, the X and y
X = sms.message
y = sms.label_num
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [555]:
# split X and y into training and validation sets - train_test_split with random_state=1138 so we all get the same
# your code here
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    sms['message'], 
    sms['label'],  
    random_state=1138
)

# Build valids
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train, 
    y_train, 
    random_state=1138
)

print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(3134,)
(1045,)
(3134,)
(1045,)


## Part 4: Vectorizing our dataset

In [556]:
# instantiate the vectorizer
vect = CountVectorizer()

### Notice

The Vectorizer (the vocabulary) is only built on the Training Set of Data. Can anyone tell me why?

The Vectorizer needs to be "fit" like a ML algorithm. Fit the <i>vect</i> with X_train

In [557]:
# your code here
# learn training data vocabulary, then use it to create a document-term matrix
X_train_dtm = vect.fit_transform(X_train)

vect.fit(X_train)


CountVectorizer()

You now need to create a dtm (document term matrix) like above by transforming the text into a matrix

In [558]:
# your code here
X_train_dtm = vect.transform(X_train)

print(X_train_dtm)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 41927 stored elements and shape (3134, 6452)>
  Coords	Values
  (0, 621)	1
  (0, 752)	1
  (0, 760)	1
  (0, 767)	1
  (0, 898)	1
  (0, 1676)	1
  (0, 1799)	1
  (0, 2655)	1
  (0, 2798)	2
  (0, 3122)	1
  (0, 3308)	1
  (0, 3400)	1
  (0, 3405)	1
  (0, 3416)	1
  (0, 3434)	3
  (0, 3522)	1
  (0, 3686)	1
  (0, 4046)	1
  (0, 4686)	1
  (0, 5092)	1
  (0, 5126)	1
  (0, 5629)	2
  (0, 5989)	1
  (1, 2384)	1
  (1, 2507)	1
  :	:
  (3132, 1898)	1
  (3132, 1901)	1
  (3132, 2016)	1
  (3132, 2639)	1
  (3132, 2732)	1
  (3132, 2836)	2
  (3132, 3138)	1
  (3132, 3234)	1
  (3132, 3461)	1
  (3132, 3999)	1
  (3132, 4049)	1
  (3132, 5069)	2
  (3132, 5705)	1
  (3132, 5782)	1
  (3132, 5793)	2
  (3132, 6202)	1
  (3132, 6336)	1
  (3133, 945)	1
  (3133, 2836)	1
  (3133, 2949)	1
  (3133, 3221)	1
  (3133, 3990)	1
  (3133, 4343)	1
  (3133, 4353)	1
  (3133, 5975)	1


In [559]:
# examine the document-term matrix
X_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 41927 stored elements and shape (3134, 6452)>

In [560]:
import numpy as np


In [561]:
for row in X_train_dtm.toarray():
     print(row)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 1]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 1 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ...

In [562]:
X_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3134, 6452))

The test data is transformed to the already fitted vocabulary. Words that were not in the original training set are ignored (our model would not know what to do with them). 

We could, of course, built this all as a pipeline using make_pipeline

In [563]:
# transform testing data (using fitted vocabulary) into a document-term matrix
# your code, make the X_test_dtm, you have already fit vect, so just transform
X_test_dtm = vect.transform(X_test)

## Part 5: Building and evaluating a model

We will use LogisticRegression to start with the default settings:

In [564]:
# import and instantiate a LogisticRegression model
from sklearn.linear_model import LogisticRegression

nb = LogisticRegression()

Note: X_train_dtm is a sparse matrix, LogisticRegression understands sparse matrices, some models may have to do conversions.

In [565]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
# Fill in below
%time nb.fit(X_train_dtm, y_train)

CPU times: user 17 ms, sys: 3.68 ms, total: 20.7 ms
Wall time: 21.7 ms


LogisticRegression()

In [566]:
# make class predictions for X_test_dtm
# Fill in below
y_pred_class = nb.predict(X_test_dtm)

In [567]:
# calculate accuracy of class predictions
from sklearn import metrics

# make class predictions for X_valid_dtm
X_valid_dtm = vect.transform(X_valid)
y_pred_class_valid = nb.predict(X_valid_dtm)

# calculate accuracy
metrics.accuracy_score(y_valid, y_pred_class_valid)

0.9779904306220095

In [568]:
nb.score(X_valid_dtm, y_valid)

0.9779904306220095

In [569]:
# print the confusion matrix
metrics.confusion_matrix(y_valid, y_pred_class_valid)

array([[884,   3],
       [ 20, 138]])

In [570]:
# print the classification report (import it if you have not already)
print(classification_report(y_valid, y_pred_class_valid))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       887
        spam       0.98      0.87      0.92       158

    accuracy                           0.98      1045
   macro avg       0.98      0.94      0.96      1045
weighted avg       0.98      0.98      0.98      1045



In [571]:
# print out all the "wrong" ones
#X_test[y_pred_class != y_valid]

X_test[y_pred_class != y_test]

1777                    Call FREEPHONE 0800 542 0578 now!
2965    Do you ever notice that when you're driving, a...
4144    In The Simpsons Movie released in July 2007 na...
4661    You call him and tell now infront of them. Cal...
305     SMS. ac Blind Date 4U!: Rodds1 is 21/m from Ab...
763     Urgent Ur £500 guaranteed award is still uncla...
1097    Dear Subscriber ur draw 4 £100 gift voucher wi...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
2402    Babe: U want me dont u baby! Im nasty and have...
1449    As a registered optin subscriber ur draw 4 £10...
3460    Not heard from U4 a while. Call me now am here...
2774    How come it takes so little time for a child w...
4729    I (Career Tel) have added u as a contact on IN...
1430    For sale - arsenal dartboard. Good condition b...
788     Ever thought about living a good life with a p...
4394    RECPT 1/3. You have ordered a Ringtone. Your o...
4676    Hi babe its Chloe, how r u? I was smashed on s...
Name: message,

In [572]:
# print message text for the false positives (ham incorrectly classified as spam)
#X_test[(y_pred_class==1) & (y_valid==0)] # or X_test[y_pred_class > y_test]
X_test[(y_pred_class==1) & (y_test==0)]

Series([], Name: message, dtype: object)

In [573]:
# print message text for the false negatives (spam incorrectly classified as ham)
#X_test[(y_pred_class==0) & (y_valid==1)]
X_test[(y_pred_class==0) & (y_test==1)]

Series([], Name: message, dtype: object)

In [574]:
# example false negative
#X_test[3132]

In [575]:
# calculate predicted probabilities for X_test_dtm (poorly calibrated probabilities)
y_pred_prob = nb.predict_proba(X_valid_dtm)[:, 1]
y_pred_prob

array([0.02009859, 0.00156622, 0.00634689, ..., 0.00720942, 0.01986224,
       0.0042337 ], shape=(1045,))

In [576]:
# calculate AUC - another metric for measure the performance of a classification system, it relies on probabilities. 
# I briefly mentioned it in lectures
metrics.roc_auc_score(y_valid, y_pred_prob)

np.float64(0.9909594280250595)

## Part 6: Comparing models

We will compare LogisticRegression with a linear Support Vector Classifier and Random Forests:

Probability=True makes it take a bit longer to train but it will allow us to calculate the roc_auc score

In [577]:
# import and instantiate a SVC model
from sklearn.svm import SVC
svcmodel = SVC(kernel='linear', probability=True)


In [578]:
# train the model using X_train_dtm
%time svcmodel.fit(X_train_dtm, y_train)

CPU times: user 1.27 s, sys: 19.8 ms, total: 1.29 s
Wall time: 1.36 s


SVC(kernel='linear', probability=True)

In [579]:
# make class predictions for X_test_dtm
y_pred_class = svcmodel.predict(X_test_dtm)

In [580]:
# calculate predicted probabilities for X_test_dtm (well calibrated)
y_pred_prob = svcmodel.predict_proba(X_test_dtm)[:, 1]

In [581]:
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.9863603732950467

In [582]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

np.float64(0.9828993666432091)

Now do Random Forests

In [583]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=1138)

# train the model using X_train_dtm
%time rf.fit(X_train_dtm, y_train)

# make class predictions for X_test_dtm
y_pred_class = rf.predict(X_test_dtm)

# calculate predicted probabilities for X_test_dtm (well calibrated)
y_pred_prob = rf.predict_proba(X_test_dtm)[:, 1]

# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

CPU times: user 724 ms, sys: 248 μs, total: 724 ms
Wall time: 736 ms


0.9798994974874372

## Part 7: Cross Validation

Now you want to do some form of cross-validation with SVC, find the best 'C', use GridSearchCV or whatever method was your favourite. Find the best cross-validation score. You can set probability=False this time around and just use the accuracy score to compare

Same with Random Forest

In [ ]:
# your code here

Now find the best 'C' with LogisticRegression using cross-validation, again find the best cross-validation score.

In [585]:
# your code here

## Part 8: Tuning the vectorizer (discussion)

All of this can go into maybe a pipeline, keep the Vectorizer options as hyperparameters that could be chosen using cross-validation

Thus far, we have been using the default parameters of [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html):

In [586]:
# show default parameters for CountVectorizer
vect

CountVectorizer()

However, the vectorizer is worth tuning, just like a model is worth tuning! Here are a few parameters that you might want to tune:

- **stop_words:** string {'english'}, list, or None (default)
    - If 'english', a built-in stop word list for English is used.
    - If a list, that list is assumed to contain stop words, all of which will be removed from the resulting tokens.
    - If None, no stop words will be used.

In [587]:
# remove English stop words
vect = CountVectorizer(stop_words='english')

In [588]:
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 24478 stored elements and shape (3134, 6196)>

- **ngram_range:** tuple (min_n, max_n), default=(1, 1)
    - The lower and upper boundary of the range of n-values for different n-grams to be extracted.
    - All values of n such that min_n <= n <= max_n will be used.

In [589]:
# include 1-grams and 2-grams
vect = CountVectorizer(ngram_range=(1, 2))

In [590]:
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 83786 stored elements and shape (3134, 33487)>

- **max_df:** float in range [0.0, 1.0] or int, default=1.0
    - When building the vocabulary, ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words).
    - If float, the parameter represents a proportion of documents.
    - If integer, the parameter represents an absolute count.

In [591]:
# ignore terms that appear in more than 50% of the documents
vect = CountVectorizer(max_df=0.5)

In [592]:
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 41927 stored elements and shape (3134, 6452)>

- **min_df:** float in range [0.0, 1.0] or int, default=1
    - When building the vocabulary, ignore terms that have a document frequency strictly lower than the given threshold. (This value is also called "cut-off" in the literature.)
    - If float, the parameter represents a proportion of documents.
    - If integer, the parameter represents an absolute count.

In [593]:
# only keep terms that appear in at least 2 documents
vect = CountVectorizer(min_df=2)

In [594]:
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 38364 stored elements and shape (3134, 2889)>

**Guidelines for tuning CountVectorizer:**

- Use your knowledge of the **problem** and the **text**, and your understanding of the **tuning parameters**, to help you decide what parameters to tune and how to tune them.
- **Experiment**, and let the data tell you the best approach!
- We could use cross-validation to make our choices! 

We can also use a pipeline like

make_pipeline(CountVectorizer(), LogisticRegression())

we can do cross-validation over the CountVectorizer parameters then

# TF-IDF

The most commonly used technique is the tf-idf short for “term frequency-inverse document frequency”, which basically reflects how important a word is to a document (email) in a collection or corpus (our set of emails or documents).

## Term frequency

Suppose we have a set of English text documents and wish to rank which document is most relevant to the query, "the brown cow". A simple way to start out is by eliminating documents that do not contain all three words "the", "brown", and "cow", but this still leaves many documents. To further distinguish them, we might count the number of times each term occurs in each document; the number of times a term occurs in a document is called its term frequency. However, in the case where the length of documents varies greatly, adjustments are often made (see definition below). The first form of term weighting is due to Hans Peter Luhn (1957) which may be summarized as:

    The weight of a term that occurs in a document is simply proportional to the term frequency.

## Inverse document frequency
Because the term "the" is so common, term frequency will tend to incorrectly emphasize documents which happen to use the word "the" more frequently, without giving enough weight to the more meaningful terms "brown" and "cow". The term "the" is not a good keyword to distinguish relevant and non-relevant documents and terms, unlike the less-common words "brown" and "cow". Hence an inverse document frequency factor is incorporated which diminishes the weight of terms that occur very frequently in the document set and increases the weight of terms that occur rarely. 


## TF-IDF

The tf-idf is an statistic that increases with the number of times a word appears in the document, penalized by the number of documents in the corpus that contain the word.

Fortunately for us, Scikit-learn has a method that does just this (sklearn.feature_extraction.text.TfidfVectorizer). See the documentation [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html)

In [595]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [596]:
#TfidfVectorizer?

In [597]:
tfidf_vectorizer = TfidfVectorizer(sublinear_tf=True, max_df=0.5, stop_words='english')

## Why these options?

TfidfVectorizer sets the vectorizer up. Here we change sublinear_tf to true, which replaces tf with 1 + log(tf). This addresses the issue that “twenty occurrences of a term in a document” does not represent “twenty times the significance of a single occurrence” [link](https://nlp.stanford.edu/IR-book/html/htmledition/sublinear-tf-scaling-1.html). Therefore, it reduces the importance of high frequency words (note that 1+log(1) = 1, while 1+log(20) = 2.3).

In [598]:
corpus = [
    "This is my first email.",
    "I'm trying to learn machine learning.",
    "This is the second email",
    "Learning is fun"
]

In [599]:
corpus_M = tfidf_vectorizer.fit_transform(corpus)

In [600]:
print(corpus_M)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (4, 7)>
  Coords	Values
  (0, 0)	1.0
  (1, 6)	0.5254727492640658
  (1, 2)	0.5254727492640658
  (1, 4)	0.5254727492640658
  (1, 3)	0.41428875116588965
  (2, 0)	0.6191302964899972
  (2, 5)	0.7852882757103967
  (3, 3)	0.6191302964899972
  (3, 1)	0.7852882757103967


In [601]:
vocabulary = tfidf_vectorizer.get_feature_names()

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

In [ ]:
print(vocabulary)

In [ ]:
pd.DataFrame(data=corpus_M.toarray(), columns=vocabulary)

In [ ]:
test = ["I’m also trying to learn python"]

In [ ]:
corpus_test = tfidf_vectorizer.transform(test)
pd.DataFrame(data=corpus_test.toarray(), columns=vocabulary)

## SMS Set

Use the SMS set to make a classifier using tfidf as our vectorizer instead of the bag of words

In [ ]:
#your code here
X_train_dtm = tfidf_vectorizer

In [ ]:
X_train_dtm

In [ ]:
X_train_dtm.toarray()

In [ ]:
.fit()

In [ ]:
X_valid_dtm = tfidf_vectorizer.transform()

In [ ]:
X_valid_dtm

In [ ]:
y_pred_class = .predict()

In [ ]:
metrics.accuracy_score()

In [ ]:
.score()

Take whatever was the best above (LogisticRegression, SVC, Random Forest) and see how it would compare with a TFIDF vectorizer